"""Adding is_section flag to question model.

Revision ID: 27d9b0a51afe
Revises: eadd37a9a581
Create Date: 2016-03-31 20:29:47.122112

"""

# revision identifiers, used by Alembic.
revision = '27d9b0a51afe'
down_revision = 'eadd37a9a581'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_section', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_section')
    ### end Alembic commands ###
