"""Adding unique constraint to table.

Revision ID: 6598bfa4b4e8
Revises: 3e4c70155c23
Create Date: 2016-02-24 02:08:16.681327

"""

# revision identifiers, used by Alembic.
revision = '6598bfa4b4e8'
down_revision = '3e4c70155c23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'module', ['code', 'institution_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='unique')
    ### end Alembic commands ###
