"""empty message

Revision ID: 821370b79800
Revises: 9c3d1d928dcc
Create Date: 2016-04-09 18:26:43.077843

"""

# revision identifiers, used by Alembic.
revision = '821370b79800'
down_revision = '9c3d1d928dcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('similar_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'similar_count')
    op.drop_column('question', 'comment_count')
    ### end Alembic commands ###
