"""Institution aggregate columns.

Revision ID: 9c3d1d928dcc
Revises: ad04219e530a
Create Date: 2016-04-09 16:32:02.363219

"""

# revision identifiers, used by Alembic.
revision = '9c3d1d928dcc'
down_revision = 'ad04219e530a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('course_count', sa.Integer(), nullable=True))
    op.add_column('institution', sa.Column('paper_count', sa.Integer(), nullable=True))
    op.add_column('institution', sa.Column('user_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'user_count')
    op.drop_column('institution', 'paper_count')
    op.drop_column('institution', 'course_count')
    ### end Alembic commands ###
